CREATE TRIGGER [Disallow_Securitychanges] ON DATABASE   
							FOR ADD_ROLE_MEMBER, DROP_ROLE_MEMBER,   
							CREATE_USER, ALTER_USER, DROP_USER,   
							CREATE_ROLE, ALTER_ROLE, DROP_ROLE,   
							GRANT_DATABASE, ALTER_AUTHORIZATION_DATABASE  
							,CREATE_SYMMETRIC_KEY, ALTER_SYMMETRIC_KEY, DROP_SYMMETRIC_KEY  
							,CREATE_ASYMMETRIC_KEY, ALTER_ASYMMETRIC_KEY, DROP_ASYMMETRIC_KEY  
							,CREATE_CERTIFICATE, ALTER_CERTIFICATE, DROP_CERTIFICATE  
							,CREATE_DATABASE_ENCRYPTION_KEY, ALTER_DATABASE_ENCRYPTION_KEY, DROP_DATABASE_ENCRYPTION_KEY  
							AS   
							IF IS_SRVROLEMEMBER('sysadmin') = 0  
							BEGIN  
							   PRINT 'Only sysadmins can perform this task, please get with the DBA team!'
							   ROLLBACK TRANSACTION  
							END

